import { Product, Category, Trend } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Novidades',
    slug: 'novidades',
    description: 'Últimos lançamentos',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800',
    order: 1,
  },
  {
    id: '2',
    name: 'Feminino',
    slug: 'feminino',
    description: 'Moda feminina',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
    order: 2,
  },
  {
    id: '3',
    name: 'Masculino',
    slug: 'masculino',
    description: 'Moda masculina',
    image: 'https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?w=800',
    order: 3,
  },
  {
    id: '4',
    name: 'Calçados',
    slug: 'calcados',
    description: 'Tênis e sapatos',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
    order: 4,
  },
  {
    id: '5',
    name: 'Acessórios',
    slug: 'acessorios',
    description: 'Bolsas, cintos e mais',
    image: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800',
    order: 5,
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Camiseta Oversized Premium',
    slug: 'camiseta-oversized-premium',
    description: 'Camiseta oversized de algodão premium com modelagem moderna e confortável. Perfeita para um visual urbano e despojado.',
    price: 149.90,
    compareAtPrice: 199.90,
    category: categories[1],
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '1-1',
        url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
        alt: 'Camiseta Oversized Preta',
        order: 0,
      },
      {
        id: '1-2',
        url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
        alt: 'Camiseta Oversized Branca',
        order: 1,
      },
    ],
    variants: [
      { id: 'v1-1', size: 'P', color: 'Preto', colorHex: '#000000', stock: 15, sku: 'COP-P-BK' },
      { id: 'v1-2', size: 'M', color: 'Preto', colorHex: '#000000', stock: 20, sku: 'COP-M-BK' },
      { id: 'v1-3', size: 'G', color: 'Preto', colorHex: '#000000', stock: 18, sku: 'COP-G-BK' },
      { id: 'v1-4', size: 'P', color: 'Branco', colorHex: '#FFFFFF', stock: 10, sku: 'COP-P-WH' },
      { id: 'v1-5', size: 'M', color: 'Branco', colorHex: '#FFFFFF', stock: 25, sku: 'COP-M-WH' },
    ],
    averageRating: 4.8,
    reviewCount: 124,
  },
  {
    id: '2',
    name: 'Calça Cargo Utilitária',
    slug: 'calca-cargo-utilitaria',
    description: 'Calça cargo com múltiplos bolsos e ajuste moderno. Design utilitário com toque contemporâneo para o dia a dia.',
    price: 299.90,
    compareAtPrice: 399.90,
    category: categories[2],
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '2-1',
        url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800',
        alt: 'Calça Cargo Bege',
        order: 0,
      },
    ],
    variants: [
      { id: 'v2-1', size: '38', color: 'Bege', colorHex: '#D2B48C', stock: 12, sku: 'CCU-38-BG' },
      { id: 'v2-2', size: '40', color: 'Bege', colorHex: '#D2B48C', stock: 8, sku: 'CCU-40-BG' },
      { id: 'v2-3', size: '42', color: 'Verde Militar', colorHex: '#4B5320', stock: 15, sku: 'CCU-42-GM' },
    ],
    averageRating: 4.6,
    reviewCount: 89,
  },
  {
    id: '3',
    name: 'Jaqueta Jeans Destroyed',
    slug: 'jaqueta-jeans-destroyed',
    description: 'Jaqueta jeans com efeito destroyed e lavagem especial. Visual autêntico e atemporal para compor looks modernos.',
    price: 449.90,
    category: categories[1],
    isFeatured: true,
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '3-1',
        url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
        alt: 'Jaqueta Jeans',
        order: 0,
      },
    ],
    variants: [
      { id: 'v3-1', size: 'P', color: 'Azul', colorHex: '#4169E1', stock: 6, sku: 'JJD-P-BL' },
      { id: 'v3-2', size: 'M', color: 'Azul', colorHex: '#4169E1', stock: 10, sku: 'JJD-M-BL' },
      { id: 'v3-3', size: 'G', color: 'Azul', colorHex: '#4169E1', stock: 8, sku: 'JJD-G-BL' },
    ],
    averageRating: 4.9,
    reviewCount: 156,
  },
  {
    id: '4',
    name: 'Tênis Chunky Branco',
    slug: 'tenis-chunky-branco',
    description: 'Tênis chunky com design robusto e solado alto. Conforto e estilo para o seu dia a dia urbano.',
    price: 379.90,
    compareAtPrice: 499.90,
    category: categories[3],
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '4-1',
        url: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800',
        alt: 'Tênis Chunky',
        order: 0,
      },
    ],
    variants: [
      { id: 'v4-1', size: '38', color: 'Branco', colorHex: '#FFFFFF', stock: 5, sku: 'TCB-38-WH' },
      { id: 'v4-2', size: '39', color: 'Branco', colorHex: '#FFFFFF', stock: 8, sku: 'TCB-39-WH' },
      { id: 'v4-3', size: '40', color: 'Branco', colorHex: '#FFFFFF', stock: 12, sku: 'TCB-40-WH' },
      { id: 'v4-4', size: '41', color: 'Branco', colorHex: '#FFFFFF', stock: 10, sku: 'TCB-41-WH' },
    ],
    averageRating: 4.7,
    reviewCount: 203,
  },
  {
    id: '5',
    name: 'Vestido Midi Floral',
    slug: 'vestido-midi-floral',
    description: 'Vestido midi com estampa floral delicada e tecido fluido. Elegância e feminilidade para ocasiões especiais.',
    price: 329.90,
    category: categories[1],
    isFeatured: true,
    isNew: true,
    isTrending: false,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '5-1',
        url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
        alt: 'Vestido Floral',
        order: 0,
      },
    ],
    variants: [
      { id: 'v5-1', size: 'P', color: 'Rosa', colorHex: '#FFB6C1', stock: 7, sku: 'VMF-P-PK' },
      { id: 'v5-2', size: 'M', color: 'Rosa', colorHex: '#FFB6C1', stock: 12, sku: 'VMF-M-PK' },
      { id: 'v5-3', size: 'G', color: 'Azul', colorHex: '#87CEEB', stock: 9, sku: 'VMF-G-BL' },
    ],
    averageRating: 4.8,
    reviewCount: 78,
  },
  {
    id: '6',
    name: 'Moletom Hoodie Premium',
    slug: 'moletom-hoodie-premium',
    description: 'Moletom hoodie de algodão premium com capuz ajustável. Conforto máximo para os dias mais frios.',
    price: 249.90,
    category: categories[2],
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '6-1',
        url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
        alt: 'Moletom Hoodie',
        order: 0,
      },
    ],
    variants: [
      { id: 'v6-1', size: 'M', color: 'Preto', colorHex: '#000000', stock: 20, sku: 'MHP-M-BK' },
      { id: 'v6-2', size: 'G', color: 'Preto', colorHex: '#000000', stock: 15, sku: 'MHP-G-BK' },
      { id: 'v6-3', size: 'GG', color: 'Cinza', colorHex: '#808080', stock: 18, sku: 'MHP-GG-GR' },
    ],
    averageRating: 4.9,
    reviewCount: 312,
  },
  {
    id: '7',
    name: 'Bolsa Crossbody Couro',
    slug: 'bolsa-crossbody-couro',
    description: 'Bolsa transversal em couro sintético de alta qualidade. Design minimalista e versátil para o dia a dia.',
    price: 189.90,
    compareAtPrice: 259.90,
    category: categories[4],
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isBestSeller: false,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '7-1',
        url: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
        alt: 'Bolsa Crossbody',
        order: 0,
      },
    ],
    variants: [
      { id: 'v7-1', size: 'Único', color: 'Preto', colorHex: '#000000', stock: 25, sku: 'BCC-U-BK' },
      { id: 'v7-2', size: 'Único', color: 'Caramelo', colorHex: '#C68E17', stock: 18, sku: 'BCC-U-CR' },
    ],
    averageRating: 4.6,
    reviewCount: 95,
  },
  {
    id: '8',
    name: 'Camisa Social Slim',
    slug: 'camisa-social-slim',
    description: 'Camisa social de corte slim em tecido de alta qualidade. Elegância e sofisticação para ocasiões formais.',
    price: 199.90,
    category: categories[2],
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isBestSeller: true,
    createdAt: new Date().toISOString(),
    images: [
      {
        id: '8-1',
        url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800',
        alt: 'Camisa Social',
        order: 0,
      },
    ],
    variants: [
      { id: 'v8-1', size: 'P', color: 'Branco', colorHex: '#FFFFFF', stock: 14, sku: 'CSS-P-WH' },
      { id: 'v8-2', size: 'M', color: 'Branco', colorHex: '#FFFFFF', stock: 22, sku: 'CSS-M-WH' },
      { id: 'v8-3', size: 'G', color: 'Azul', colorHex: '#4169E1', stock: 16, sku: 'CSS-G-BL' },
    ],
    averageRating: 4.7,
    reviewCount: 142,
  },
];

export const trends: Trend[] = [
  {
    id: '1',
    name: 'Streetwear Essentials',
    slug: 'streetwear-essentials',
    description: 'Peças essenciais do streetwear para compor looks urbanos e modernos',
    image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=1200',
    products: [products[0], products[1], products[5]],
    startDate: new Date().toISOString(),
    isActive: true,
  },
  {
    id: '2',
    name: 'Primavera 2024',
    slug: 'primavera-2024',
    description: 'Tendências frescas e coloridas para a primavera',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200',
    products: [products[4], products[6]],
    startDate: new Date().toISOString(),
    isActive: true,
  },
  {
    id: '3',
    name: 'Mais Vendidos',
    slug: 'mais-vendidos',
    description: 'Os produtos favoritos dos nossos clientes',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200',
    products: [products[1], products[3], products[5], products[7]],
    startDate: new Date().toISOString(),
    isActive: true,
  },
];
